/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventAnmeldungRouteImport } from './routes/event-anmeldung'
import { Route as BewerbungRouteImport } from './routes/bewerbung'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventAnmeldungRoute = EventAnmeldungRouteImport.update({
  id: '/event-anmeldung',
  path: '/event-anmeldung',
  getParentRoute: () => rootRouteImport,
} as any)
const BewerbungRoute = BewerbungRouteImport.update({
  id: '/bewerbung',
  path: '/bewerbung',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bewerbung': typeof BewerbungRoute
  '/event-anmeldung': typeof EventAnmeldungRoute
  '/events': typeof EventsRoute
  '/kontakt': typeof KontaktRoute
  '/roster': typeof RosterRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bewerbung': typeof BewerbungRoute
  '/event-anmeldung': typeof EventAnmeldungRoute
  '/events': typeof EventsRoute
  '/kontakt': typeof KontaktRoute
  '/roster': typeof RosterRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bewerbung': typeof BewerbungRoute
  '/event-anmeldung': typeof EventAnmeldungRoute
  '/events': typeof EventsRoute
  '/kontakt': typeof KontaktRoute
  '/roster': typeof RosterRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bewerbung'
    | '/event-anmeldung'
    | '/events'
    | '/kontakt'
    | '/roster'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bewerbung'
    | '/event-anmeldung'
    | '/events'
    | '/kontakt'
    | '/roster'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bewerbung'
    | '/event-anmeldung'
    | '/events'
    | '/kontakt'
    | '/roster'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BewerbungRoute: typeof BewerbungRoute
  EventAnmeldungRoute: typeof EventAnmeldungRoute
  EventsRoute: typeof EventsRoute
  KontaktRoute: typeof KontaktRoute
  RosterRoute: typeof RosterRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-anmeldung': {
      id: '/event-anmeldung'
      path: '/event-anmeldung'
      fullPath: '/event-anmeldung'
      preLoaderRoute: typeof EventAnmeldungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewerbung': {
      id: '/bewerbung'
      path: '/bewerbung'
      fullPath: '/bewerbung'
      preLoaderRoute: typeof BewerbungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BewerbungRoute: BewerbungRoute,
  EventAnmeldungRoute: EventAnmeldungRoute,
  EventsRoute: EventsRoute,
  KontaktRoute: KontaktRoute,
  RosterRoute: RosterRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
